# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Generate project files
        run: scripts\premake5.exe vs2019 --os=windows --file=scripts\premake5.lua

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
        
      - name: Run MSBuild
        run: msbuild.exe D3D12.sln /p:Configuration=Release /p:Platform=x64
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v2.2.3
        with:
          name: Artifacts
          path: Build/
